name: PickupMoney
main: com.gmail.vkhanh234.PickupMoney.PickupMoney
author: KickVN
version: 1.3.2
softdepend: [Vault]
commands:
   pickupmoney:
      description: Show PickupMoney's Command.
      usage: /pum
      aliases: [pum, pmoney]
permissions:
    PickupMoney.command:
        description: Allows you to use command.
        default: op
    PickupMoney.pickup:
        description: Allows you to pick up money.
        default: op